name: "🚀 Feature Request"
description: "I have a specific suggestion!"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: markdown
    attributes:
      value: |
        Please make sure you have checked the [roadmap](https://github.com/users/melkati/projects/3) to ensure that your feature request does not already exist.

  - type: checkboxes
    id: input2
    attributes:
      label: Have you checked the roadmap to ensure your feature request does not already exist?
      options:
        - label: Yes, I have checked the roadmap and my feature request does not already exist.

  - type: checkboxes
    id: input1
    attributes:
      label: Would you like to work on this feature?
      options:
        - label: Check this if you would like to implement a PR, we are more than happy to help you go through the process.

  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: |
        A concise description of what the problem is.
      placeholder: |
        I would like to be able to [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered

  - type: textarea
    attributes:
      label: Documentation, Adoption, Migration Strategy
      description: |
        If you can, explain how users will be able to use this and how it might be documented.
        You can add images or diagrams if you want by dragging and dropping them here.
